# Generated by Django 3.0.8 on 2021-07-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210711_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.CharField(choices=[('North America', 'North America'), ('South America', 'South America'), ('Europe', 'Europe'), ('Middle East', 'Middle East'), ('Africa', 'Africa'), ('Asia', 'Asia')], max_length=200),
        ),
    ]
