# Generated by Django 3.0.8 on 2021-07-13 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20210713_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='modeules',
            field=models.CharField(choices=[('Web Ticketing', 'Web Ticketing'), ('Appointment', 'Appointment'), ('Queue Management', 'Queue Management'), ('Others', 'Others')], max_length=200),
        ),
    ]
