# Generated by Django 3.0.8 on 2021-07-13 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20210713_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='modeules',
            new_name='modules',
        ),
    ]
