# Generated by Django 3.0.8 on 2021-07-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20210713_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
