# Generated by Django 3.0.8 on 2021-07-15 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_project_projectname'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
