# Generated by Django 3.0.8 on 2021-07-29 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20210715_1203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webticket', models.CharField(max_length=200, null=True)),
                ('appointment', models.CharField(max_length=200, null=True)),
                ('watsapp', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='modules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.Modules'),
        ),
    ]
