# Generated by Django 3.0.8 on 2021-07-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20210729_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='modules',
        ),
        migrations.AddField(
            model_name='project',
            name='appointment',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='watsapp',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='webticket',
            field=models.BooleanField(null=True),
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
    ]
