# Generated by Django 3.0.8 on 2021-07-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20210729_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='count',
            field=models.IntegerField(null=True),
        ),
    ]
