# Generated by Django 3.0.8 on 2021-08-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_project_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='modules',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
