# Generated by Django 3.0.8 on 2021-08-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_project_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='queue',
            field=models.BooleanField(null=True),
        ),
    ]
